### ISSUE TITLE
The color of statusBar

### ISSUE THREAD

**Issue by p1raya** [nonylene/vscode-dark-molokai-theme#1]
The color of statusBar is not specified:
"statusBar.background"
"statusBar.noFolderBackground"
"statusBar.debuggingBackground"

**Comment by nonylene** [comment]
This theme follows [Default Dark theme](https://github.com/Microsoft/vscode/blob/master/extensions/theme-defaults/themes/dark_defaults.json) for UI colors (includes statusBar). Default Dark theme does not set statusBar color so [default color](https://github.com/microsoft/vscode/blob/92ae7d6da67f6866c9234dc730f65b742c9268e1/src/vs/workbench/common/theme.ts#L264) is used.

P.S.  Today I added `statusBarItem.remoteForgrand, Background` from dark theme https://github.com/nonylene/vscode-dark-molokai-theme/commit/1a41679b183139e009dac77b7aee58a78a498ae4.
