### ISSUE TITLE
SCM message bar selection highlighting invisible

### ISSUE THREAD

**Issue by kalemas** [nonylene/vscode-dark-molokai-theme#2]
![2020-01-22_15-15-13](https://user-images.githubusercontent.com/638393/72893434-092baf00-3d2a-11ea-8c87-c77b6fc663a2.gif)

**Comment by nonylene** [comment]
[Fix](4ae5e30) has been released in v1.0.1. 

![image](https://user-images.githubusercontent.com/7397316/72960490-34c59c80-3df1-11ea-97b4-373be79e7827.png)

**Comment by nonylene** [comment]
This issue reappears again in 1.0.2

**Comment by nonylene** [comment]
![image](https://user-images.githubusercontent.com/7397316/100108507-326b1d80-2eae-11eb-92a1-f27a16b94398.png)

**Comment by nonylene** [comment]
This is due to the behavior that VSCode uses `editor.selectionBackground` color as the selection background color in SCM tab unlike other tabs.

I have just submitted the issue to the VSCode: https://github.com/microsoft/vscode/issues/124407

**Comment by nonylene** [comment]
SCM tab issue has been resolved and released on stable 🎉

**Comment by kalemas** [comment]
confirm, Search, Source Control, Marketplace have correct highlighting. Thank you!
