### ISSUE TITLE
method is highlighted like variables

### ISSUE THREAD

**Issue by delavecker** [nonylene/vscode-dark-molokai-theme#3]
![image](https://user-images.githubusercontent.com/67975223/100036970-fd909500-2ddf-11eb-99c7-732f982e8342.png)

Is it possible to change the color of methods, preferably a different color than funcitons? A good example below:

![image](https://user-images.githubusercontent.com/67975223/100037101-42b4c700-2de0-11eb-89b9-5deec3a17196.png)

Thanks, great theme!

**Comment by nonylene** [comment]
Your request is pretty good but this theme follows the default Monokai theme for highlighting. I won't add my own colors as much as possible. 

Alternatively, you can override the theme in settings. For example in `settings.json`:

```
    "editor.tokenColorCustomizations": {
        "textMateRules": [
            {
                "scope": "meta.member.access meta.function-call.generic",
                "settings": {
                    "foreground": "#A6E22E"
                }
            },
        ]
    },
```

**Comment by delavecker** [comment]
Is that the exact place to change the color of methods? 
I've just started my journey on programming, anyway, thanks for the reply!

**Comment by nonylene** [comment]
> Is that the exact place to change the color of methods?

I think so. Confirmed on my environment.

**Comment by delavecker** [comment]
man, I changed it here. Officially my preferred one (I tested many others), thank you so much
